name: Development CI

on:
  push:
    branches: [ develop, feature/* ]
  pull_request:
    branches: [ develop, main ]

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'

jobs:
  # Tests et validation du code
  test:
    name: Tests et Validation
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: saveos123
          POSTGRES_USER: saveos
          POSTGRES_DB: saveos
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8 black isort

    - name: Code formatting check (Black)
      run: black --check api/ worker/ agent/

    - name: Import sorting check (isort)
      run: isort --check-only api/ worker/ agent/

    - name: Linting (flake8)
      run: flake8 api/ worker/ agent/ --max-line-length=100 --ignore=E203,W503

    - name: Type checking (mypy)
      run: |
        pip install mypy
        mypy api/ worker/ agent/ --ignore-missing-imports || true

    - name: Run Python tests
      env:
        DATABASE_URL: postgresql://saveos:saveos123@localhost:5432/saveos
        REDIS_URL: redis://localhost:6379/0
      run: |
        python test_local.py || true  # Tests peuvent échouer sans Docker
        
    - name: Test database schema
      env:
        DATABASE_URL: postgresql://saveos:saveos123@localhost:5432/saveos
      run: |
        python -c "
        from api.database import create_tables, engine
        create_tables()
        print('✅ Schema de base de données validé')
        "

  # Tests de l'interface web
  web-test:
    name: Tests Interface Web
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Install dependencies
      working-directory: web
      run: npm ci

    - name: Type checking
      working-directory: web
      run: npm run build

    - name: Lint check
      working-directory: web
      run: npm run lint

  # Tests Docker
  docker-test:
    name: Tests Docker
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Validate docker-compose
      run: docker-compose config

    - name: Build images
      run: |
        docker-compose build --no-cache
        
    - name: Test services startup
      run: |
        docker-compose up -d
        sleep 30
        
        # Vérifier que les services sont up
        docker-compose ps
        
        # Test de santé de l'API
        timeout 60 bash -c 'until curl -k -f https://localhost:8000/health; do sleep 2; done'
        
        # Test de l'interface web
        timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'
        
        echo "✅ Tous les services sont opérationnels"

    - name: Cleanup
      if: always()
      run: docker-compose down -v

  # Analyse de sécurité
  security:
    name: Analyse de Sécurité
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Bandit (Python security)
      run: |
        pip install bandit
        bandit -r api/ worker/ agent/ -f json -o bandit-report.json || true

    - name: Upload security report
      uses: actions/upload-artifact@v3
      with:
        name: security-report
        path: bandit-report.json

  # Build léger pour développement
  build-dev:
    name: Build Development
    runs-on: ubuntu-latest
    needs: [test, web-test]
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Build Python package (dev)
      run: |
        pip install build
        python -m build

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Build web interface (dev)
      working-directory: web
      run: |
        npm ci
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dev-build-artifacts
        path: |
          dist/
          web/.next/



  # Notification
  notify:
    name: Notifications
    runs-on: ubuntu-latest
    needs: [test, web-test, security]
    if: always()
    
    steps:
    - name: Notify on success
      if: needs.test.result == 'success' && needs.web-test.result == 'success'
      run: |
        echo "✅ Tous les tests de développement sont passés!"
        # Ici, ajouter des notifications (Slack, Discord, email, etc.)

    - name: Notify on failure
      if: needs.test.result == 'failure' || needs.web-test.result == 'failure'
      run: |
        echo "❌ Certains tests de développement ont échoué!"
        # Ici, ajouter des notifications d'échec